name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: |
          npm ci
          npm run build
      - name: Render markdown
        uses: ./
        id: markdown
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          command: markdown.render
          text: '#beep\nboop!'
      - name: Print
        run: echo "${response}"
        env:
          response: ${{ steps.markdown.outputs.response }}
